### ISSUE TITLE
I updated the mod and stuck on loading screen

### ISSUE THREAD

**Issue by Xrezeneus** [JamesVeug/AgainstTheStormAPI#1]
Even after getting back to the old version issue still continued 
[Player.log](https://github.com/user-attachments/files/16488496/Player.log)

**Comment by JamesVeug** [comment]
Theres a few issues in those logs that i can see but the first one indicates your game files are corrupt sonehow.
If you're on steam you can verify game files which should fix the issue otherwose reonstalling could help.

Another issue is simple rebalance mod is broken and uninstalling that could also resolve the issue.

Likewise of any mod issues try uninstalling mods 1 by 1 to check when the loading works and that will tell you which one is breaking the game.

**Comment by Xrezeneus** [comment]
You were definitely right the one caused the problem was simple reblance mod it was playable last time ı played but something happened to the mod ı think whatever thanks for helping me
