### ISSUE TITLE
[Request New Feature] Set `HookedEffectBuilder` Retroactive & Preview text key

### ISSUE THREAD

**Issue by Forwindzz** [JamesVeug/AgainstTheStormAPI#2]
Hi, I want to add 2 api functions in `class HookedEffectBuilder`.
The api currently has `HookedEffectBuilder.SetPreviewDescription`, but does not have `SetPreviewDescriptionKey`. It might be a bit wired, compare to the api design of `SetDescriptionKey` and `SetDescription`
So, I would like to request two new api `SetPreviewDescriptionKey` and `SetRetroactiveDescriptionKey` in `HookedEffectBuilder`.
```C# 
HookedEffectBuilder builder = new(PluginInfo.PLUGIN_GUID, cornerstoneName, cornerstoneIconPath);
builder.SetDescriptionKey($"description_key"); //invoke EffectBuilder<T>.SetDescriptionKey() method
builder.SetDisplayNameKey($"displayName_key");//invoke EffectBuilder<T>.SetDisplayNameKey() method
// API does not have these two methods :(
builder.SetPreviewDescriptionKey($"preview_key"); 
builder.SetRetroactiveDescriptionKey($"retroactive_key");
```

**Comment by JamesVeug** [comment]
Ah they were definitely missed!
Added and ready for v2.3.0
